#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'runit'
cookbook 'nginx', :git => 'git://github.com/opscode-cookbooks/nginx.git'
cookbook 'java', :git => 'git@github.com:opscode-cookbooks/java.git'
cookbook 'rbenv', :git => 'git@github.com:fnichol/chef-rbenv.git'
cookbook 'ruby_build'
cookbook 'ark'
cookbook 'maven'
